-- Refuse an unsafe preexisting role or inherited PUBLIC privileges rather than
-- quietly retaining domain access or changing unrelated application ACLs.
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='genjishimada_queue_worker') THEN
        BEGIN
            CREATE ROLE genjishimada_queue_worker LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
        EXCEPTION WHEN duplicate_object OR unique_violation THEN
            -- Roles are cluster-wide: another database's migration can create
            -- this same role after the existence check. Validate it below.
            NULL;
        END;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='genjishimada_queue_worker'
        AND (rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls OR rolinherit))
       OR EXISTS (SELECT 1 FROM pg_auth_members m JOIN pg_roles r ON r.oid=m.member WHERE r.rolname='genjishimada_queue_worker')
       OR EXISTS (SELECT 1 FROM pg_namespace n WHERE n.nspname NOT LIKE 'pg_%'
           AND n.nspname <> 'information_schema' AND has_schema_privilege('genjishimada_queue_worker',n.oid,'CREATE'))
       OR EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
           WHERE n.nspname NOT LIKE 'pg_%' AND n.nspname <> 'information_schema'
           AND c.relkind IN ('r','p','v','m','f')
           AND NOT (n.nspname='public' AND c.relname IN ('pgqueuer','pgqueuer_log','pgqueuer_statistics','pgqueuer_schedules'))
           AND has_schema_privilege('genjishimada_queue_worker',n.oid,'USAGE')
           AND (has_table_privilege('genjishimada_queue_worker',c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
               OR has_any_column_privilege('genjishimada_queue_worker',c.oid,'SELECT,INSERT,UPDATE,REFERENCES'))) THEN
        RAISE EXCEPTION 'Queue worker has unsafe inherited privileges; remove domain/PUBLIC grants, schema CREATE, elevated role powers or memberships before migration';
    END IF;
END $$;

-- PGQueuer 1.1.1 schema, generated from its pinned QueryBuilderEnvironment.
CREATE TYPE pgqueuer_status AS ENUM ('queued', 'picked', 'successful', 'exception', 'canceled', 'deleted', 'failed');
    CREATE  TABLE pgqueuer (
        id BIGSERIAL PRIMARY KEY,
        priority INT NOT NULL,
        queue_manager_id UUID,
        created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        updated TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        execute_after TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        status pgqueuer_status NOT NULL,
        entrypoint TEXT NOT NULL,
        dedupe_key TEXT,
        payload BYTEA,
        headers JSONB,
        attempts INT NOT NULL DEFAULT 0
    );
    CREATE INDEX pgqueuer_priority_id_id1_idx ON pgqueuer (priority ASC, id DESC)
        INCLUDE (id) WHERE status = 'queued';
    CREATE INDEX pgqueuer_updated_id_id1_idx ON pgqueuer (updated ASC, id DESC)
        INCLUDE (id) WHERE status = 'picked';
    CREATE INDEX pgqueuer_queue_manager_id_idx ON pgqueuer (queue_manager_id)
        WHERE queue_manager_id IS NOT NULL;
    CREATE INDEX pgqueuer_ep_prio_id_idx ON pgqueuer (entrypoint, priority DESC, id ASC)
        WHERE status = 'queued';
    CREATE INDEX pgqueuer_ep_ea_idx ON pgqueuer (entrypoint, execute_after)
        WHERE status = 'queued';
    CREATE UNIQUE INDEX IF NOT EXISTS pgqueuer_unique_dedupe_key ON
        pgqueuer (dedupe_key) WHERE ((status IN ('queued', 'picked') AND dedupe_key IS NOT NULL));

    CREATE  TABLE pgqueuer_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        job_id BIGINT NOT NULL,
        status pgqueuer_status NOT NULL,
        priority INT NOT NULL,
        entrypoint TEXT NOT NULL,
        traceback JSONB DEFAULT NULL,
        aggregated BOOLEAN DEFAULT FALSE
    );
    CREATE INDEX pgqueuer_log_not_aggregated ON pgqueuer_log (entrypoint, priority, status, created) WHERE not aggregated;
    CREATE INDEX pgqueuer_log_created ON pgqueuer_log (created);
    CREATE INDEX pgqueuer_log_status ON pgqueuer_log (status);
    CREATE INDEX pgqueuer_log_job_id_status ON pgqueuer_log (job_id, created DESC);

    CREATE  TABLE pgqueuer_statistics (
        id BIGSERIAL PRIMARY KEY,
        created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT DATE_TRUNC('sec', NOW() at time zone 'UTC'),
        count BIGINT NOT NULL,
        priority INT NOT NULL,
        status pgqueuer_status NOT NULL,
        entrypoint TEXT NOT NULL
    );
    CREATE UNIQUE INDEX pgqueuer_statistics_unique_count ON pgqueuer_statistics (
        priority,
        DATE_TRUNC('sec', created at time zone 'UTC'),
        status,
        entrypoint
    );

    CREATE  TABLE pgqueuer_schedules (
        id BIGSERIAL PRIMARY KEY,
        expression TEXT NOT NULL, -- Crontab-like schedule definition (e.g., '* * * * *')
        entrypoint TEXT NOT NULL,
        heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        created TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        updated TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        next_run TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        last_run TIMESTAMP WITH TIME ZONE,
        status pgqueuer_status DEFAULT 'queued',
        UNIQUE (expression, entrypoint)
    );

    CREATE FUNCTION fn_pgqueuer_changed() RETURNS TRIGGER AS $$
    DECLARE
        to_emit BOOLEAN := false;  -- Flag to decide whether to emit a notification
    BEGIN
        -- Check operation type and set the emit flag accordingly
        IF TG_OP = 'UPDATE' AND OLD IS DISTINCT FROM NEW THEN
            to_emit := true;
        ELSIF TG_OP = 'DELETE' THEN
            to_emit := true;
        ELSIF TG_OP = 'INSERT' THEN
            to_emit := true;
        ELSIF TG_OP = 'TRUNCATE' THEN
            to_emit := true;
        END IF;

        -- Perform notification if the emit flag is set
        IF to_emit THEN
            PERFORM pg_notify(
                'ch_pgqueuer',
                json_build_object(
                    'channel', 'ch_pgqueuer',
                    'operation', lower(TG_OP),
                    'sent_at', NOW(),
                    'table', TG_TABLE_NAME,
                    'type', 'table_changed_event'
                )::text
            );
        END IF;

        -- Return appropriate value based on the operation
        IF TG_OP IN ('INSERT', 'UPDATE') THEN
            RETURN NEW;
        ELSIF TG_OP = 'DELETE' THEN
            RETURN OLD;
        ELSE
            RETURN NULL; -- For TRUNCATE and other non-row-specific contexts
        END IF;

    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER tg_pgqueuer_changed
    AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON pgqueuer
    EXECUTE FUNCTION fn_pgqueuer_changed();
        
-- Stable application identity outlives the active PGQueuer row.
ALTER TABLE public.jobs
    ADD COLUMN queue_job_id bigint UNIQUE,
    ADD COLUMN event_key text,
    ADD COLUMN payload_hash text,
    ADD COLUMN payload bytea,
    ADD COLUMN schema_version integer NOT NULL DEFAULT 1,
    ADD COLUMN entity_key text,
    ADD COLUMN event_sequence bigint GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN handler_failures integer NOT NULL DEFAULT 0,
    ADD COLUMN retry_generation integer NOT NULL DEFAULT 0,
    ADD COLUMN depends_on uuid REFERENCES public.jobs(id);
CREATE UNIQUE INDEX jobs_event_identity ON public.jobs(action,event_key) WHERE event_key IS NOT NULL;
CREATE INDEX jobs_entity_order ON public.jobs(entity_key,event_sequence) WHERE entity_key IS NOT NULL;
ALTER TABLE public.pgqueuer ADD COLUMN handler_failures integer NOT NULL DEFAULT 0,
    ADD COLUMN failure_code text, ADD COLUMN failure_message text;
CREATE INDEX pgqueuer_failed_dependencies ON public.pgqueuer(entrypoint,id)
    WHERE status='failed' AND failure_code='dependency_failed';

CREATE TABLE public.job_effects (
    job_id uuid NOT NULL REFERENCES public.jobs(id), effect_key text NOT NULL,
    kind text NOT NULL CHECK (kind IN ('mutation','external','alert')),
    state text NOT NULL CHECK (state IN ('started','completed','resend')),
    fingerprint text NOT NULL, destination text, result jsonb,
    manager_id uuid, claimed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(job_id,effect_key)
);
CREATE TABLE public.job_operations (
    request_id text PRIMARY KEY, job_id uuid NOT NULL REFERENCES public.jobs(id),
    operator_id bigint NOT NULL, action text NOT NULL, generation integer NOT NULL,
    reason text, result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.job_alerts (
    job_id uuid PRIMARY KEY REFERENCES public.jobs(id),
    guild_id bigint, channel_id bigint, message_id bigint,
    notified_generation integer, rendered_generation integer, rendered_status text,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.job_imports (
    source_id text PRIMARY KEY, job_id uuid REFERENCES public.jobs(id),
    disposition text NOT NULL, reason text NOT NULL, payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Queue-only workers cannot write domain tables. This narrow trigger projects
-- queue transitions into the public status record within the same transaction.
CREATE FUNCTION public.project_queue_state() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
BEGIN
    UPDATE public.jobs SET status = (CASE NEW.status WHEN 'picked' THEN 'processing'
        WHEN 'failed' THEN 'failed' ELSE 'queued' END)::public.job_status,
        handler_failures=NEW.handler_failures, attempts=NEW.attempts,
        error_code=NEW.failure_code, error_msg=NEW.failure_message,
        started_at=CASE WHEN NEW.status='picked' THEN COALESCE(started_at,now()) ELSE started_at END,
        finished_at=CASE WHEN NEW.status='failed' THEN now() ELSE NULL END
    WHERE queue_job_id=NEW.id;
    IF NEW.status='failed' THEN
        INSERT INTO public.job_alerts(job_id) SELECT id FROM public.jobs WHERE queue_job_id=NEW.id
        ON CONFLICT(job_id) DO UPDATE SET updated_at=now();
    END IF;
    RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.project_queue_state() FROM PUBLIC;
CREATE TRIGGER project_queue_state AFTER UPDATE ON public.pgqueuer
FOR EACH ROW EXECUTE FUNCTION public.project_queue_state();

CREATE FUNCTION public.project_queue_terminal() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE completed_id uuid;
BEGIN
    IF NEW.status='successful' AND NOT EXISTS (SELECT 1 FROM public.pgqueuer WHERE id=NEW.job_id) THEN
        UPDATE public.jobs SET status='succeeded',finished_at=now(),error_code=NULL,error_msg=NULL
        WHERE queue_job_id=NEW.job_id RETURNING id INTO completed_id;
        UPDATE public.pgqueuer q SET status='queued',execute_after=now(),queue_manager_id=NULL,
            failure_code=NULL,failure_message=NULL
        FROM public.jobs j WHERE j.queue_job_id=q.id AND j.depends_on=completed_id
            AND q.status='failed' AND q.failure_code='dependency_failed'
            AND j.error_code IS DISTINCT FROM 'discarded'
            AND NOT EXISTS (SELECT 1 FROM public.job_effects e
                WHERE e.job_id=j.id AND e.kind='external' AND e.state='started');
    END IF;
    RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION public.project_queue_terminal() FROM PUBLIC;
CREATE TRIGGER project_queue_terminal AFTER INSERT ON public.pgqueuer_log
FOR EACH ROW EXECUTE FUNCTION public.project_queue_terminal();

-- Terminal log writes can overlap: a parent may finish before its child's held
-- failure is visible to the terminal trigger. Reconcile durable state on every
-- worker poll so either commit ordering is eventually released. Restrict this
-- definer to the one safe transition; workers still cannot read application jobs.
CREATE FUNCTION public.release_ready_job_dependencies(entrypoints text[]) RETURNS void
LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
    WITH ready AS (
        SELECT q.id FROM public.pgqueuer q
        JOIN public.jobs child ON child.queue_job_id=q.id
        JOIN public.jobs parent ON parent.id=child.depends_on
        WHERE q.entrypoint=ANY(entrypoints) AND q.status='failed'
            AND q.failure_code='dependency_failed' AND parent.status='succeeded'
            AND child.error_code IS DISTINCT FROM 'discarded'
            AND NOT EXISTS (SELECT 1 FROM public.job_effects e
                WHERE e.job_id=child.id AND e.kind='external' AND e.state='started')
        ORDER BY q.id LIMIT 100 FOR UPDATE OF q SKIP LOCKED
    )
    UPDATE public.pgqueuer q SET status='queued',execute_after=now(),updated=now(),
        queue_manager_id=NULL,failure_code=NULL,failure_message=NULL
    FROM ready WHERE q.id=ready.id;
$$;
REVOKE ALL ON FUNCTION public.release_ready_job_dependencies(text[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.release_ready_job_dependencies(text[]) TO genjishimada_queue_worker;

GRANT USAGE ON SCHEMA public TO genjishimada_queue_worker;
GRANT SELECT, UPDATE, DELETE ON public.pgqueuer TO genjishimada_queue_worker;
GRANT INSERT ON public.pgqueuer_log TO genjishimada_queue_worker;
GRANT USAGE ON SEQUENCE public.pgqueuer_log_id_seq TO genjishimada_queue_worker;
GRANT SELECT ON public.pgqueuer_statistics, public.pgqueuer_schedules TO genjishimada_queue_worker;
REVOKE ALL ON public.jobs,public.job_effects,public.job_operations,public.job_alerts,public.job_imports FROM PUBLIC;
