"""Spike 006 — map-durability.

Concern (raised by the user): a map added via the endpoint lives ONLY in the running DB.
If the DB is ever rebuilt from migrations, every dynamically-added map vanishes — names
*and* the maps.mastery FK rows pointing at them. Today maps.names is seeded by 63 plain
INSERTs in 0001_init.sql (not even idempotent — re-running errors on duplicate PK).

This spike makes the failure tangible and proves a durable strategy, all inside a
throwaway schema `spike006` that is DROPPED at the end — the real data is never touched.

Strategy proven: the endpoint writes ONLY to the DB (stays instant/automatic); a separate
EXPORT step regenerates a committed, idempotent seed file from the DB. Migration-only
rebuilds replay that seed; backups remain the primary recovery path.

Run:
    uv run --env-file ../../../.env.local --with asyncpg python durability.py
"""

from __future__ import annotations

import asyncio
import os
from pathlib import Path

import asyncpg

SCHEMA = "spike006"
SEED_FILE = Path(__file__).parent / "maps_names.seed.sql"

INITIAL_MAPS = ["Circuit Royal", "Hanamura", "Busan"]  # mimics the 0001_init.sql baseline


def line(c: str = "─") -> str:
    return c * 70


def plain_seed(maps: list[str]) -> str:
    """How 0001_init.sql writes it today — NOT idempotent."""
    return "\n".join(f"INSERT INTO {SCHEMA}.names (name) VALUES ('{m}');" for m in maps)


def idempotent_seed(maps: list[str]) -> str:
    """The durable export: safe to replay any number of times."""
    rows = ",\n".join(f"    ('{m}')" for m in sorted(maps))
    return (f"-- generated by export step from {SCHEMA}.names — safe to replay\n"
            f"INSERT INTO {SCHEMA}.names (name) VALUES\n{rows}\nON CONFLICT DO NOTHING;\n")


async def names(conn: asyncpg.Connection) -> list[str]:
    return [r["name"] for r in await conn.fetch(f"SELECT name FROM {SCHEMA}.names ORDER BY name")]


async def rebuild_from(conn: asyncpg.Connection, seed_sql: str) -> None:
    """Simulate 'drop & rebuild from migrations': wipe the table, replay the seed."""
    await conn.execute(f"TRUNCATE {SCHEMA}.names CASCADE")
    await conn.execute(seed_sql)


async def main() -> None:
    print(line("="))
    print(" SPIKE 006 — map-durability (throwaway schema, real data untouched)")
    print(line("="))

    conn = await asyncpg.connect(
        host=os.environ.get("POSTGRES_HOST", "localhost"),
        port=int(os.environ.get("POSTGRES_PORT", "5432")),
        user=os.environ["POSTGRES_USER"],
        password=os.environ["POSTGRES_PASSWORD"],
        database=os.environ["POSTGRES_DB"],
    )
    try:
        await conn.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE")
        await conn.execute(f"CREATE SCHEMA {SCHEMA}")
        await conn.execute(f"CREATE TABLE {SCHEMA}.names (name text PRIMARY KEY)")

        # --- baseline seed (today's plain style) ----------------------------
        print("\n[1] Apply the baseline seed (today's 0001_init.sql plain INSERT style)")
        await conn.execute(plain_seed(INITIAL_MAPS))
        print(f"    seeded: {await names(conn)}")

        print("\n[2] Re-run the SAME plain seed (simulating a re-applied migration) ...")
        try:
            await conn.execute(plain_seed(INITIAL_MAPS))
            print("    re-run OK")
        except asyncpg.UniqueViolationError as e:
            print(f"    FAILS — {e}")
            print("    FINDING: the real seed is not even idempotent; can't be safely replayed.")

        # --- a map arrives via the endpoint (DB-only write) -----------------
        print("\n[3] Admin adds a map via endpoint -> INSERT into the live DB only")
        await conn.execute(f"INSERT INTO {SCHEMA}.names (name) VALUES ('Throne of Anubis')")
        print(f"    live DB now: {await names(conn)}")

        # --- FAILURE PATH: rebuild from migrations alone --------------------
        print("\n[4] FAILURE PATH — rebuild from migrations alone (baseline seed only)")
        await rebuild_from(conn, plain_seed(INITIAL_MAPS))
        after = await names(conn)
        print(f"    after rebuild: {after}")
        assert "Throne of Anubis" not in after
        print("    ✗ 'Throne of Anubis' is GONE — exactly the user's concern, reproduced.")

        # --- FIX PATH: export -> committed idempotent seed ------------------
        print("\n[5] FIX PATH — re-add the map, then EXPORT the DB to a committed seed")
        await conn.execute(f"INSERT INTO {SCHEMA}.names (name) VALUES ('Throne of Anubis')")
        exported = idempotent_seed(await names(conn))
        SEED_FILE.write_text(exported)
        print(f"    wrote {SEED_FILE.name} (the version-controlled source of truth):")
        for ln in exported.splitlines():
            print(f"        {ln}")

        print("\n[6] Rebuild from the EXPORTED seed ...")
        await rebuild_from(conn, SEED_FILE.read_text())
        after = await names(conn)
        print(f"    after rebuild: {after}")
        assert "Throne of Anubis" in after
        print("    ✓ 'Throne of Anubis' SURVIVED the rebuild.")

        print("\n[7] Replay the exported seed again (idempotency) ...")
        await conn.execute(SEED_FILE.read_text())
        print(f"    re-run OK, still: {await names(conn)}")
    finally:
        await conn.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE")
        await conn.close()
        print(f"\n[8] dropped schema {SCHEMA} — real DB untouched.")

    print("\n" + line())
    print(" Findings:")
    print(" - Migration-only rebuild loses dynamic maps (reproduced in [4]).")
    print(" - An EXPORTED idempotent seed (from the DB) survives rebuilds AND is")
    print("   safely replayable — unlike today's plain INSERTs.")
    print(" - Endpoint stays DB-only (instant/automatic); export is a SEPARATE job,")
    print("   never on the request path. Backups remain the primary recovery path.")
    print(line())


if __name__ == "__main__":
    asyncio.run(main())
