-- generated by export step from spike006.names — safe to replay
INSERT INTO spike006.names (name) VALUES
    ('Busan'),
    ('Circuit Royal'),
    ('Hanamura'),
    ('Throne of Anubis')
ON CONFLICT DO NOTHING;
