"""Service-layer domain exceptions."""

from .auth import (  # noqa: I001
    AuthError,
    EmailAlreadyExistsError,
    EmailAlreadyVerifiedError,
    EmailValidationError,
    InvalidCredentialsError,
    PasswordValidationError,
    RateLimitExceededError,
    TokenAlreadyUsedError,
    TokenExpiredError,
    TokenInvalidError,
    UserNotFoundError,
    UsernameValidationError,
)
from .completions import (
    CompletionNotFoundError,
    CompletionsError,
    DuplicateCompletionError,
    DuplicateFlagError,
    DuplicateQualityVoteError,
    DuplicateUpvoteError,
    DuplicateVerificationError,
    MapNotFoundError as CompletionsMapNotFoundError,
    SlowerThanPendingError,
)
from .lootbox import (
    InsufficientKeysError,
    LootboxError,
)
from .maps import (
    AlreadyInPlaytestError,
    CreatorNotFoundError,
    DuplicateCreatorError,
    DuplicateGuideError,
    DuplicateMechanicError,
    DuplicateRestrictionError,
    DuplicateTagsError,
    EditRequestNotFoundError,
    GuideNotFoundError,
    InvalidEditResolutionError,
    LinkedMapError,
    MapCodeExistsError,
    MapNotFoundError,
    MapsError,
    MapValidationError,
    MasteryUpdateFailedError,
    PendingEditRequestExistsError,
)
from .playtest import (
    InvalidPatchError,
    PlaytestError,
    PlaytestNotFoundError,
    PlaytestStateError,
    VoteConstraintError,
    VoteNotFoundError,
)
from .users import (
    InvalidUserIdError,
    UserAlreadyExistsError,
    UserNotFoundError as UsersUserNotFoundError,
    UsersError,
)

__all__ = [
    "AlreadyInPlaytestError",
    "AuthError",
    "CompletionNotFoundError",
    "CompletionsError",
    "CompletionsMapNotFoundError",
    "CreatorNotFoundError",
    "DuplicateCompletionError",
    "DuplicateCreatorError",
    "DuplicateFlagError",
    "DuplicateGuideError",
    "DuplicateMechanicError",
    "DuplicateQualityVoteError",
    "DuplicateRestrictionError",
    "DuplicateTagsError",
    "DuplicateUpvoteError",
    "DuplicateVerificationError",
    "EditRequestNotFoundError",
    "EmailAlreadyExistsError",
    "EmailAlreadyVerifiedError",
    "EmailValidationError",
    "GuideNotFoundError",
    "InsufficientKeysError",
    "InvalidCredentialsError",
    "InvalidEditResolutionError",
    "InvalidPatchError",
    "InvalidUserIdError",
    "LinkedMapError",
    "LootboxError",
    "MapCodeExistsError",
    "MapNotFoundError",
    "MapValidationError",
    "MapsError",
    "MasteryUpdateFailedError",
    "PasswordValidationError",
    "PendingEditRequestExistsError",
    "PlaytestError",
    "PlaytestNotFoundError",
    "PlaytestStateError",
    "RateLimitExceededError",
    "SlowerThanPendingError",
    "TokenAlreadyUsedError",
    "TokenExpiredError",
    "TokenInvalidError",
    "UserAlreadyExistsError",
    "UserNotFoundError",
    "UsernameValidationError",
    "UsersError",
    "UsersUserNotFoundError",
    "VoteConstraintError",
    "VoteNotFoundError",
]
