"""Service-layer domain exceptions."""

from .auth import (  # noqa: I001
    AuthError,
    EmailAlreadyExistsError,
    EmailAlreadyVerifiedError,
    EmailValidationError,
    InvalidCredentialsError,
    PasswordValidationError,
    RateLimitExceededError,
    TokenAlreadyUsedError,
    TokenExpiredError,
    TokenInvalidError,
    UserNotFoundError,
    UsernameValidationError,
)
from .lootbox import (
    InsufficientKeysError,
    LootboxError,
)
from .maps import (
    AlreadyInPlaytestError,
    CreatorNotFoundError,
    DuplicateCreatorError,
    DuplicateGuideError,
    DuplicateMechanicError,
    DuplicateRestrictionError,
    EditRequestNotFoundError,
    GuideNotFoundError,
    InvalidEditResolutionError,
    LinkedMapError,
    MapCodeExistsError,
    MapNotFoundError,
    MapsError,
    MapValidationError,
    MasteryUpdateFailedError,
    PendingEditRequestExistsError,
)
from .playtest import (
    InvalidPatchError,
    PlaytestError,
    PlaytestNotFoundError,
    PlaytestStateError,
    VoteConstraintError,
    VoteNotFoundError,
)

__all__ = [
    "AlreadyInPlaytestError",
    "AuthError",
    "CreatorNotFoundError",
    "DuplicateCreatorError",
    "DuplicateGuideError",
    "DuplicateMechanicError",
    "DuplicateRestrictionError",
    "EditRequestNotFoundError",
    "EmailAlreadyExistsError",
    "EmailAlreadyVerifiedError",
    "EmailValidationError",
    "GuideNotFoundError",
    "InsufficientKeysError",
    "InvalidCredentialsError",
    "InvalidEditResolutionError",
    "InvalidPatchError",
    "LinkedMapError",
    "LootboxError",
    "MapCodeExistsError",
    "MapNotFoundError",
    "MapValidationError",
    "MapsError",
    "MasteryUpdateFailedError",
    "PasswordValidationError",
    "PendingEditRequestExistsError",
    "PlaytestError",
    "PlaytestNotFoundError",
    "PlaytestStateError",
    "RateLimitExceededError",
    "TokenAlreadyUsedError",
    "TokenExpiredError",
    "TokenInvalidError",
    "UserNotFoundError",
    "UsernameValidationError",
    "VoteConstraintError",
    "VoteNotFoundError",
]
